//===========================================================================
// Verilog module generated by IPexpress    03/23/2019    09:13:23       
// Filename  : csi2_4to1_1_params.v                                    
// IP Package: 4:1 CSI-2 to CSI-2 1.1                           
// Copyright(c) 2016 Lattice Semiconductor Corporation. All rights reserved. 
//===========================================================================
`define   RX_CLK_MODE_HS_ONLY
`define   RAW10
`define   NO_OF_LANE_1
`define   RX_GEAR_8
`define   TX_GEAR_8
`define   LR
`define   TX_WAIT_LESS_15MS
`define   PLL_CM 8'd192
`define   PLL_CN 5'd0
`define   PLL_CO 2'd0
`define   TX_FREQ_TGT 120
`define   TINIT_VALUE 500
`define   VC_CH0 2'b00
`define   VC_CH1 2'b01
`define   LANE_COUNT 1
`define   NUM_TX_LANE_1
`define   NUM_RX_LANE_1
`define   LP_1
`define   CSI2CSI
`define   TX_CSI2
`define   TX_CLK_MODE_HS_ONLY
