//==================================================================================
// Verilog module generated by Clarity Designer    03/23/2019    09:13:24       
// Filename: csi2_4to1_1_dphy_rx_wrap.v                                                         
// Filename: 4:1 CSI-2 to CSI-2 1.1                                    
// Copyright(c) 2016 Lattice Semiconductor Corporation. All rights reserved.        
//==================================================================================

module csi2_4to1_1_dphy_rx_wrap (
    input wire                reset_n_i,
    input wire                reset_byte_n_i,
    input wire                reset_byte_fr_n_i,
    input wire                clk_byte_fr_i,
    inout wire                clk_p_i,
    inout wire                clk_n_i,
    inout wire                d0_p_io,	
    inout wire                d0_n_io,	
    input wire                term_clk_en_i,
    input wire                term_d0_en_i,
    input wire                term_d1_en_i,
    input wire                term_d2_en_i,
    input wire                term_d3_en_i,
    input wire                hs_d0_en_i,
    input wire                hs_d1_en_i,
    input wire                hs_d2_en_i,
    input wire                hs_d3_en_i,
    input wire                lp_d0_tx_en_i,
    input wire                lp_d0_tx_p_i,
    input wire                lp_d0_tx_n_i,

    output wire               clk_hs_o,
    output wire               clk_byte_o,
    output wire [8-1:0] bd0_o,
    output wire [8-1:0] bd1_o,
    output wire [8-1:0] bd2_o,
    output wire [8-1:0] bd3_o,
    output wire               hs_sync_o,       // aligned to B8(Gear8) or B800(Gear16)

    output wire               lp_clk_rx_p_o,
    output wire               lp_clk_rx_n_o,
    output wire               lp_d0_rx_p_o,
    output wire               lp_d0_rx_n_o,
    output wire               lp_d1_rx_p_o,
    output wire               lp_d1_rx_n_o,
    output wire               lp_d2_rx_p_o,
    output wire               lp_d2_rx_n_o,
    output wire               lp_d3_rx_p_o,
    output wire               lp_d3_rx_n_o,
    output wire               cd_clk_o,
    output wire               cd_d0_o
);

dphy_rx_wrap
#(
    .NUM_RX_LANE    (1),
    .RX_GEAR        (8),
    .DPHY_RX_IP     ("LATTICE"),
    .LANE_ALIGN     ("OFF"),
    .BYTECLK_MHZ    (60.000),
//// added parameters for customizing lane aligner
    .FIFO_DEPTH     (16),
    .FIFO_TYPE0     ("EBR"),
    .FIFO_TYPE1     ("EBR"),
    .FIFO_TYPE2     ("EBR"),
    .FIFO_TYPE3     ("EBR")
)
csi_rx (
    .reset_n_i        (reset_n_i),
    .reset_byte_n_i   (reset_byte_n_i),
    .reset_byte_fr_n_i(reset_byte_fr_n_i),
    .clk_byte_fr_i    (clk_byte_fr_i),
    .clk_p_i          (clk_p_i),
    .clk_n_i          (clk_n_i),
    .d0_p_io          (d0_p_io),
    .d0_n_io          (d0_n_io),
    .term_clk_en_i    (term_clk_en_i),
    .term_d0_en_i     (term_d0_en_i),
    .term_d1_en_i     (term_d1_en_i),
    .term_d2_en_i     (term_d2_en_i),
    .term_d3_en_i     (term_d3_en_i),
    .hs_d0_en_i       (hs_d0_en_i),
    .hs_d1_en_i       (hs_d1_en_i),
    .hs_d2_en_i       (hs_d2_en_i),
    .hs_d3_en_i       (hs_d3_en_i),
    .lp_d0_tx_en_i    (lp_d0_tx_en_i),
    .lp_d0_tx_p_i     (lp_d0_tx_p_i),
    .lp_d0_tx_n_i     (lp_d0_tx_n_i),

    .clk_hs_o         (clk_hs_o), // byte clk output. used to clock hs_ctrl_d0
    .clk_byte_o       (clk_byte_o),  // used to latch data
    .bd0_o            (bd0_o),
    .bd1_o            (bd1_o),
    .bd2_o            (bd2_o),
    .bd3_o            (bd3_o),
    .hs_sync_o        (hs_sync_o),

    .lp_clk_rx_p_o    (lp_clk_rx_p_o),
    .lp_clk_rx_n_o    (lp_clk_rx_n_o),
    .lp_d0_rx_p_o     (lp_d0_rx_p_o),
    .lp_d0_rx_n_o     (lp_d0_rx_n_o),
    .lp_d1_rx_p_o     (lp_d1_rx_p_o),
    .lp_d1_rx_n_o     (lp_d1_rx_n_o),
    .lp_d2_rx_p_o     (lp_d2_rx_p_o),
    .lp_d2_rx_n_o     (lp_d2_rx_n_o),
    .lp_d3_rx_p_o     (lp_d3_rx_p_o),
    .lp_d3_rx_n_o     (lp_d3_rx_n_o),
    .cd_clk_o         (cd_clk_o),
    .cd_d0_o          (cd_d0_o)
);

endmodule
