//==================================================================================
// Verilog module generated by Clarity Designer    03/17/2019    11:26:36       
// Filename: csi2_4to1_1_tx_byte_data_gen_bb.v                                                         
// Filename: 4:1 CSI-2 to CSI-2 1.1                                    
// Copyright(c) 2016 Lattice Semiconductor Corporation. All rights reserved.        
//==================================================================================

module csi2_4to1_1_tx_byte_data_gen(		
  input                       rst_n_i,
  input                       tx_clk,

  input                       lbf_lastwd_ch0,
  input [8*2-1:0] byte_bufout_ch0,
  input [8*2-1:0] byte_bufout_ch1,
  input                       lbfr_wdvalid_ch0,
  input                       lbfr_wdvalid_ch1,
  input [15:0]                rd_counter_ch0, 

  output [63:0]           gen_word_o,
  output                  gen_data_valid_o
);

endmodule
