//==================================================================================
// Verilog module generated by Clarity Designer    03/23/2019    09:13:24       
// Filename: csi2_4to1_1_tx_global_operation.v                                                         
// Filename: 4:1 CSI-2 to CSI-2 1.1                                    
// Copyright(c) 2016 Lattice Semiconductor Corporation. All rights reserved.        
//==================================================================================

module csi2_4to1_1_tx_global_operation (
  // clock and reset
  input wire                       reset_n,
  input wire                       core_clk,
  // interface signals from pkt header and footer
  input wire                       dphy_pkten_i,
  input wire [4*16-1:0] dphy_pkt_i,

  input wire                       clk_hs_en_i,
  input wire                       d_hs_en_i,

  output wire                      d_hs_rdy_o, 
  // interface to DCI wrapper
  // HS i/f
  output wire                      hs_clk_gate_en_o,
  output wire                      hs_clk_en_o,
  output wire                      hs_data_en_o,
  output wire [16-1:0]  hs_data_d0_o,
  output wire                      c2d_ready_o,
 
  // LP i/f
  output wire                      lp_clk_en_o,
  output wire                      lp_clk_p_o,
  output wire                      lp_clk_n_o,
  output wire                      lp_data_en_o,
  output wire                      lp_data_p_o,
  output wire                      lp_data_n_o
);

tx_global_operation #(
////added support for HS_ONLY
  .CLK_MODE    ("HS_ONLY"),
  .LANE_WIDTH  (1),
  .DATA_WIDTH  (16),
  .GEAR_16     (0),
  .TX_FREQ_TGT (120),
  .LPHS_FIFO_IMPL ("LUT")
)
tx_global_operation_inst (
  // clock and reset
  .reset_n          (reset_n),
  .core_clk         (core_clk),
  // interface signals from pkt header and footer
  .dphy_pkten_i     (dphy_pkten_i),
  .dphy_pkt_i       (dphy_pkt_i),

  .clk_hs_en_i      (clk_hs_en_i),
  .d_hs_en_i        (d_hs_en_i),

  .d_hs_rdy_o       (d_hs_rdy_o),
  // interface to DCI wrapper
  // HS i/f
  .hs_clk_gate_en_o (hs_clk_gate_en_o),
  .hs_clk_en_o      (hs_clk_en_o),
  .hs_data_en_o     (hs_data_en_o),
  .hs_data_d0_o     (hs_data_d0_o),
  .c2d_ready_o      (c2d_ready_o),
  // LP i/f
  .lp_clk_en_o      (lp_clk_en_o),
  .lp_clk_p_o       (lp_clk_p_o),
  .lp_clk_n_o       (lp_clk_n_o),
  .lp_data_en_o     (lp_data_en_o),
  .lp_data_p_o      (lp_data_p_o),
  .lp_data_n_o      (lp_data_n_o)
);

endmodule
