//==================================================================================
// Verilog module generated by Clarity Designer    03/23/2019    09:13:23       
// Filename: csi2_4to1_1_line_buffer_bb.v                                                         
// Filename: 4:1 CSI-2 to CSI-2 1.1                                    
// Copyright(c) 2016 Lattice Semiconductor Corporation. All rights reserved.        
//==================================================================================

module csi2_4to1_1_line_buffer
(
  input                          rst_n_i,
  input                          reset_rx_n_i,
  input                          reset_tx_n_i,
  input                          rx_clk_i,
  input                          tx_clk_i,
  input                          d2c_payload_en_i,	
  input [8-1:0]      byte_i,
  input [15:0]                   d2c_wc_i,
  input                          hdr_rd_lbfr_en,
  input [15:0]                   hdr_wdcnt,
  input                          lp_en,
  output  [15:0] 		 rd_counter,
  output  [8-1:0] byte_o,
  output                      word_valid_o,
  output                      empty_o,
  output                      lbfr_halffull,
  output                      lbf_lastwd
) ;

endmodule
