//==================================================================================
// Verilog module generated by Clarity Designer    03/23/2019    09:13:24       
// Filename: csi2_4to1_1_tinit_count_bb.v                                                         
// Filename: 4:1 CSI-2 to CSI-2 1.1                                    
// Copyright(c) 2016 Lattice Semiconductor Corporation. All rights reserved.        
//==================================================================================

module csi2_4to1_1_tinit_count (
  input wire    clk	,
  input wire    resetn	,
  output wire   tinit_done_o
);

endmodule

