//==================================================================================
// Verilog module generated by Clarity Designer    03/23/2019    09:13:24       
// Filename: csi2_4to1_1_hdr_buffer_bb.v                                                         
// Filename: 4:1 CSI-2 to CSI-2 1.1                                    
// Copyright(c) 2016 Lattice Semiconductor Corporation. All rights reserved.        
//==================================================================================

module csi2_4to1_1_hdr_buffer
(
 input 		   rst_n_i,
 input 		   reset_tx_n_i,
 input 		   reset_rx_n_i,
 input 		   tx_clk_i,
 input 		   rx_clk_i,
 input 		   d2c_sp_en_i,
 input 		   d2c_lp_en_i,
 input [7:0] 	   d2c_ph_i,
 input [15:0] 	   d2c_wc_i,
 input 		   d2c_payload_en_i,
 input 		   arb_rdy,
 input 		   arb_gnt,
 input             c2d_hs_rdy,
 input             c2d_ld_pyld,
 input             c2d_phdr_done,
 input 		   lbf_txrdy,
 input 		   lbf_lastwd_ch0,

 input 		   lbf_lastwd_ch1,  
 output 	   hdr_rd_lbfr_en1, 
 
 output  	   hdr_rd_lbfr_en0,
 output  	   hdr_req,
 output  [15:0]    hdr_wdcnt,
 output  [5:0]     hdr_dtype,
 output  [1:0]     hdr_chID,
 output  	   hdr_SPtype, 
 output  	   hdr_xfrdone

);

endmodule
