//==================================================================================
// Verilog module generated by Clarity Designer    03/23/2019    09:13:24       
// Filename: csi2_4to1_1_tx_global_operation_bb.v                                                         
// Filename: 4:1 CSI-2 to CSI-2 1.1                                    
// Copyright(c) 2016 Lattice Semiconductor Corporation. All rights reserved.        
//==================================================================================

module csi2_4to1_1_tx_global_operation (
  // clock and reset
  input wire                       reset_n,
  input wire                       core_clk,
  // interface signals from pkt header and footer
  input wire                       dphy_pkten_i,
  input wire [4*16-1:0] dphy_pkt_i,

  input wire                       clk_hs_en_i,
  input wire                       d_hs_en_i,

  output wire                      d_hs_rdy_o,
  // interface to DCI wrapper
  // HS i/f
  output wire                      hs_clk_gate_en_o,
  output wire                      hs_clk_en_o,
  output wire                      hs_data_en_o,
  output wire [16-1:0]  hs_data_d0_o,
  output wire                      c2d_ready_o,
 
  // LP i/f
  output wire                      lp_clk_en_o,
  output wire                      lp_clk_p_o,
  output wire                      lp_clk_n_o,
  output wire                      lp_data_en_o,
  output wire                      lp_data_p_o,
  output wire                      lp_data_n_o
);

endmodule
