//==================================================================================
// Verilog module generated by Clarity Designer    03/23/2019    09:13:24       
// Filename: csi2_4to1_1_line_buffer.v                                                         
// Filename: 4:1 CSI-2 to CSI-2 1.1                                    
// Copyright(c) 2016 Lattice Semiconductor Corporation. All rights reserved.        
//==================================================================================

module csi2_4to1_1_line_buffer

(
  input                          rst_n_i,
  input                          reset_rx_n_i,
  input                          reset_tx_n_i,
  input                          rx_clk_i,
  input                          tx_clk_i,
  input                          d2c_payload_en_i,	
  input [8-1:0]      byte_i,
  input [15:0]                   d2c_wc_i,
  input                          hdr_rd_lbfr_en,
  input [15:0]                   hdr_wdcnt,
  input                          lp_en,
  output  [15:0] 		 rd_counter,
  output  [8-1:0] byte_o,
  output                      word_valid_o,
  output                      empty_o,
  output                      lbfr_halffull,
  output                      lbf_lastwd
);


line_buffer
#(
.LANE_COUNT    (1),
.TX_DATA_WIDTH (8),
.RX_DATA_WIDTH (8),
.BUFFER_DEPTH  (2048),
.CHANNEL_ID    (0)
)
line_buffer (
.rst_n_i                      (rst_n_i),
.reset_tx_n_i                 (reset_tx_n_i),
.reset_rx_n_i                 (reset_rx_n_i),
.lp_en                        (lp_en),
.rx_clk_i                     (rx_clk_i),
.tx_clk_i                     (tx_clk_i),
.d2c_payload_en_i             (d2c_payload_en_i),
.byte_i                       (byte_i),
.d2c_wc_i                     (d2c_wc_i),
.hdr_rd_lbfr_en               (hdr_rd_lbfr_en),
.hdr_wdcnt                    (hdr_wdcnt),
.rd_counter                   (rd_counter),
.byte_o                       (byte_o),
.word_valid_o                 (word_valid_o),
.lbfr_halffull                (lbfr_halffull),
.empty_o                      (empty_o),
.lbf_lastwd                   (lbf_lastwd)
);

endmodule
